randomly set relations to avoid mongodb error when seeding
strapi/strapi-template-blog pull request #9
Opened 2021-07-20 09:33 UTC by markkaylor

2021-07-21 13:29 UTC, remidej requested changes
You didn't lie, that approach is quite creative 😄 

I think having random relations is much better than an error. But it's also not as good as having the right ones all the time. So do you think we could only keep the "random" solution for Mongoose, and keep the current system for SQL databases?

Also, it looks like you've applied some code formatting here. But I think the previous style matches the Strapi codebase better, since all Strapi files use double quotes and semi colons

2021-07-27 08:54 UTC, remidej reviewed
It's working well 🙂 

Just remove the remaining console log then we can merge this

2021-07-27 08:54 UTC, remidej commented on template/config/functions/bootstrap.js
> +      console.log(entry);
Let's remove this log

2021-07-27 08:58 UTC, markkaylor commented on template/config/functions/bootstrap.js
> +      console.log(entry);
woops, will do

2021-07-27 12:22 UTC, remidej approved these changes

2021-07-27 12:34 UTC, merged